name: GitHub Actions Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]

jobs:
  Explore-GitHub-Actions:
    if: contains(github.event.head_commit.message, '/run-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' #Copy contents of deployment.json in GitHub Secrets
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build Deployment Container 
        run: |-
          cd ${{ github.workspace }}/src/deployment/
          docker build -t test-app-deployment -f Dockerfile .
      - name: Run Deploy App
        if: contains(github.event.head_commit.message, '/run-deploy-app')
        run: |-
          docker run --rm --name test-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.ssh:/home/app/.ssh \
            -v ${{ github.workspace }}/src/frontend-simple:/frontend-simple \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/data-collector:/data-collector \
            -v ${{ github.workspace }}/src/data-processor:/data-processor \
            --volume $GITHUB_WORKSPACE:/workspace \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            --env GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project \
            -e GCP_ZONE=us-central1-a \
            test-app-deployment sh deploy-from-actions.sh
      - name: Run Data Collector
        if: contains(github.event.head_commit.message, '/run-data-collector')
        run: |-
          docker run --rm --name test-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-simple:/frontend-simple \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/data-collector:/data-collector \
            -v ${{ github.workspace }}/src/data-processor:/data-processor \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=mushroom-app-ml-workflow-demo \
            -e GCS_SERVICE_ACCOUNT=ml-workflow@ac215-project.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://mushroom-app-trainer-code \
            test-app-deployment python cli.py --data_collector
      - name: Run Data Processor
        if: contains(github.event.head_commit.message, '/run-data-processor')
        run: |-
          docker run --rm --name test-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-simple:/frontend-simple \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/data-collector:/data-collector \
            -v ${{ github.workspace }}/src/data-processor:/data-processor \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=mushroom-app-ml-workflow-demo \
            -e GCS_SERVICE_ACCOUNT=ml-workflow@ac215-project.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://mushroom-app-trainer-code \
            test-app-deployment python cli.py --data_processor
      - run: echo "🍏 This job's status is ${{ job.status }}."